spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/quotes
spring.datasource.username=quotes
spring.datasource.password=quotes
spring.jpa.hibernate.ddl-auto=update
server.port=8081